import api from './client';
export const getAttendees = (params) => api.get('/attendees', { params });
export const exportAttendees = (params) => api.get('/attendees/export', { params, responseType: 'blob' });
export const getAttendee = (id) => api.get(`/attendees/${id}`);
export const createAttendee = (data) => api.post('/attendees', data);
export const updateAttendee = (id, data) => api.patch(`/attendees/${id}`, data);
export const inviteAttendee = (id) => api.post(`/attendees/${id}/invite`);
export const inviteAttendeeByTicket = (ticketId, email) => api.post(`/attendees/invite-by-ticket/${ticketId}`, { email });
export const verifyPhoto = (id, data) => api.patch(`/attendees/${id}/verify-photo`, data);
export const rejectPhoto = (data) => api.post('/attendees/reject-photo', data);
export const getResubmitInfo = (token) => api.get(`/attendees/resubmit/${token}`);
export const resubmitPhoto = (formData) => api.post('/attendees/resubmit/photo', formData);
export const bulkUpload = (formData) => api.post('/attendees/bulk-upload', formData);
export const downloadTemplate = () => api.get('/attendees/template', { responseType: 'blob' });
export const getConfirmInfo = (token) => api.get(`/attendees/confirm/${token}`);
export const confirmIdentity = (token, formData) => api.post(`/attendees/confirm/${token}`, formData);
export const getInviteInfo = (token) => api.get(`/invite/${token}`);
export const respondToInvite = (data) => api.post('/invite/respond', data);
export const confirmInvite = (formData) => api.post('/invite/confirm', formData);
export const assignTicket = (data) => api.post('/tickets/assign', data);
export const inviteTicket = (data) => api.post('/tickets/invite', data);
